### ISSUE TITLE
test database orm

### ISSUE THREAD

**Issue by francescobianco** [kenstuddy/Simple-PHP-MVC-Framework#1]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by kenstuddy** [comment]
Thank you for your effort in opening this issue. I personally feel that this is beyond the scope of what I had in mind for this project. This is designed to be a very simple PHP MVC framework with little reliance on dependencies other than Composer itself (for autoloading) and maybe a simple UI dependency. You are more than welcome to fork this repository and implement that library yourself. Please let me know if you have any other questions.
